---
AWSTemplateFormatVersion: "2010-09-09"
Description: 'Creacion de RDS Amazon Aurora-MySQL Cluster'
# Metadata
Metadata:
  # Se puede definir su propia agrupacion y ordenacion de parametros para que
  # los usuarios puedan especificar de manera eficiente los valores de los parametros.
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Parametros de la VPC"
        Parameters:
          - VpcIdParameter
      - Label:
          default: 'Configuracion Amazon RDS (Amazon Aurora/MySQL) Cluster Redundante'
        Parameters:
          - DBClusterIdentifierName
          - DBEngineVersion
          - DBInstanceClass
          - DBSubnets
          - DBPermitLocation
          - DBName
          - DBSecretName
          - DBMasterUsername
          - DBPreferredBackupWindow
          - DBBackupRetentionPeriod
          - DBPreferredMaintenanceWindow
          - DBAutoMinorVersionUpgrade
          - DBDeletionProtection
    ParameterLabels:
      # ParameterLable VPC
      VpcIdParameter:
        default: 'Debe de seleccionar una VPC para Amazon Aurora-Mysql Cluster'
      # ParameterLabels RDS
      DBClusterIdentifierName:
        default: 'Debe de ingresar un nombre para el Amazon Aurora-Mysql Cluster'
      DBEngineVersion:
        default: 'Escoger el Engine y Version de Amazon Aurora-Mysql'
      DBInstanceClass:
        default: 'Tipo de instancia para el Cluster Amazon Aurora-MySQL'
      DBSubnets:
        default: 'Debe de seleccionar las Subnets que utilizara el Cluster Amazon Aurora-MySQL'
      DBPermitLocation:
        default: 'Ingrese CIDR para permitir acceso al Cluster de Aurora-Mysql'
      DBName:
        default: 'Ingrese el nombre de la base de datos a crear'
      DBSecretName:
        default: 'Ingrese el nombre del Secret'
      DBMasterUsername:
        default: 'Nombre del usuario con privilegios de administrador en el Cluster de Aurora-Mysql'
      DBPreferredBackupWindow:
        default: 'Ingrese el intervalo de tiempo diario en UTC durante el cual desea crear los backups de manera automaticas'
      DBBackupRetentionPeriod:
        default: 'Periodo de retencion para el backup de la base de datos'
      DBPreferredMaintenanceWindow:
        default: 'El rango de tiempo semanal (en UTC) durante el cual se puede realizar el mantenimiento del sistema.'
      DBAutoMinorVersionUpgrade:
        default: 'Actualizacion automatica para las nuevas Minor Versions de Amazon Aurora-MySQL'
      DBDeletionProtection:
        default: 'Indicar si se habilita la proteccion contra eliminacion del Amazon Aurora-MySQL Cluster'
# Parameters
Parameters:
  # Definimos VPC a usar para la configuracion del ambiente
  VpcIdParameter:
    Description: Escoger sobre que VPC a trabajar
    Type: 'AWS::EC2::VPC::Id'
  DBSubnets:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: 'Seleccione las Subnets a utilizar el Cluster Aurora-MySQL'
  # Parametros Base de Datos
  DBClusterIdentifierName:
    Type: String
    MinLength: 1
    MaxLength: 60
    Default: 'mi-cluster1'
    AllowedPattern: ^(?!-)(?!.*--)(?!.*-$)[a-z][a-z0-9-]*$
    Description: |
      - El nombre debe ser unico en todos los clusteres de base de datos que tiene en su cuenta de AWS en la region de AWS actual. //
      - Debe contener como minimo 1 caracter y un maximo de 60 caracteres. //
      - Los caracteres permitidos son: letras minusculas, numeros y guiones. //
      - El primer caracter debe ser una letra minuscula. //
      - No debe contener dos guiones consecutivos.
      - No debe de terminar con un guion.
    ConstraintDescription: |-
      - Debe contener como minimo 1 caracter y un maximo de 60 caracteres. //
      - Los caracteres permitidos son: letras minusculas, numeros y guiones. //
      - El primer caracter debe ser una letra minuscula. //
      - No debe contener dos guiones consecutivos.
      - No debe de terminar con un guion.
  DBEngineVersion:
    # aws rds describe-db-engine-versions --engine aurora-mysql --query 'DBEngineVersions[?contains(SupportedEngineModes,`provisioned`)].EngineVersion'
    Type: String
    AllowedValues: ['5.7.mysql-aurora.2.10.2', '8.0.mysql-aurora.3.02.0']
    Default: '8.0.mysql-aurora.3.02.0'
    Description: 'Engine y Version de Amazon Aurora-Mysql'
  DBInstanceClass:
    Type: String
    # https://docs.aws.amazon.com/es_es/AmazonRDS/latest/AuroraUserGuide/Concepts.DBInstanceClass.html#Concepts.DBInstanceClass.SupportAurora
    AllowedValues: [ 'db.t3.medium', 'db.t3.large',
                     'db.t4g.medium', 'db.t4g.large',
                     'db.r5.large', 'db.r5.xlarge', 'db.r5.2xlarge', 'db.r5.4xlarge', 'db.r5.8xlarge', 'db.r5.12xlarge', 'db.r5.16xlarge', 'db.r5.24xlarge',
                     'db.r6g.large', 'db.r6g.xlarge', 'db.r6g.2xlarge', 'db.r6g.4xlarge', 'db.r6g.8xlarge', 'db.r6g.12xlarge', 'db.r6g.16xlarge']
    Default: 'db.t3.medium'
    Description: |
      El nombre de la clase de capacidad de computo y memoria de Amazon RDS
      (Aurora-MySQL) instancia de base de datos.
    ConstraintDescription: Debe seleccionar un tipo de instancia de base de datos valido.
  DBPermitLocation:
    Type: String
    MinLength: 9
    MaxLength: 18
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    Default: '0.0.0.0/0'
    Description: |
      El rango de direcciones IP que se pueden usar para conectar al Cluster de Aurora-MySQL
    ConstraintDescription: Debe ser un rango CIDR de IP valido con el formato x.x.x.x/x.
  DBName:
    Type: String
    Default: 'mibd'
    MinLength: 4
    MaxLength: 64
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    Description: |
      - Nombre de la base de datos a crear. //
      - Debe contener como minimo 4 caracter y un maximo de 64 caracteres. //
      - Solo se permiten caracteres alfanumericos. //
      - Debe de comenzar con una letra.
    ConstraintDescription: |
      - Debe contener como minimo 4 caracter y un maximo de 32 caracteres. //
      - Solo se permiten caracteres alfanumericos. //
      - Debe de comenzar con una letra.
  DBSecretName:
    Type: String
    Default: 'dev/bi/telered'
    MinLength: 4
    MaxLength: 32
    AllowedPattern: '^[a-zA-Z][a-zA-Z\d/_+=.@-]*$'
    Description: |
      - El nombre de secret a crear para utilizarlo con el Cluster Aurora-MySQL //
      - Debe contener como minimo 4 caracter y un maximo de 32 caracteres. //
      - Solo se permiten caracteres alfanumericos y los siguientes caracteres especiales: /_+=.@-
      - Debe de comenzar con una letra.
  DBMasterUsername:
    Type: String
    Default: 'admin'
    MinLength: 4
    MaxLength: 32
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    Description: |
      - El nombre de usuario con privilegios de administrador de la base de datos //
      - Debe contener como minimo 4 caracter y un maximo de 32 caracteres. //
      - Solo se permiten caracteres alfanumericos. //
      - Debe de comenzar con una letra.
    ConstraintDescription: |
      - Debe contener como minimo 1 caracter y un maximo de 32 caracteres. //
      - Solo se permiten caracteres alfanumericos. //
      - Debe de comenzar con una letra.
  DBPreferredBackupWindow:
    Type: String
    Default: '05:20-05:55'
    AllowedPattern: ^(([0-1][0-9]|2[0-3]):[0-5][0-9])\-(([0-1][0-9]|2[0-3]):[0-5][0-9])?$
    Description: |
      - Debe tener el formato hh24:mi-hh24:mi. //
      - Debe estar en tiempo universal coordinado (UTC). //
      - No debe entrar en conflicto con la ventana de mantenimiento preferida. //
      - Debe ser de al menos 30 minutos.
    ConstraintDescription: |-
      - Debe tener el formato hh24:mi-hh24:mi. //
      - Debe estar en tiempo universal coordinado (UTC). //
      - No debe entrar en conflicto con la ventana de mantenimiento preferida. //
      - Debe ser de al menos 30 minutos.
  DBBackupRetentionPeriod:
    Type: Number
    Default: 7
    MinValue: 1
    MaxValue: 35
    Description: |
      - El numero de dias durante los cuales se retienen los snapshots de base de datos de forma automatica.
      - El numero de dias minimo es 1 y un maximo de 35.
  DBPreferredMaintenanceWindow:
    Type: String
    Default: 'Sat:07:00-Sat:07:30'
    AllowedPattern: ^((Mon|Tue|Wed|Thu|Fri|Sat|Sun):([0-1][0-9]|2[0-3]):([0-5][0-9]))\-((Mon|Tue|Wed|Thu|Fri|Sat|Sun):([0-1][0-9]|2[0-3]):([0-5][0-9]))$
    Description: |
      - Ingrese el periodo en el que desea modificaciones pendientes (como cambiar la clase de instancia de base de datos)
      o parches aplicados a la instancia de base de datos por parte de Amazon RDS. //
      - Cualquier mantenimiento de este tipo debe iniciarse y completarse dentro del periodo seleccionado. //
      - El periodo o ventana debe de ser de 30 minutos como minimo. //
      - Si no ingresa un periodo, Amazon RDS asignara una ventana de 30 minutos seleccionada al azar de un bloque de tiempo
        de 8 horas para cada region de AWS, que ocurre en un dia aleatorio de la semana. //
      - El formato es: ddd:hh24:mi-ddd:hh24:mi
    ConstraintDescription: La ventana debe de ser 30 minutos como minimo.
  DBAutoMinorVersionUpgrade:
    Type: String
    AllowedValues: ['true', 'false']
    Default: 'true'
    Description: Seleccione true/false para configurar el Auto Minor Version upgrade
  DBDeletionProtection:
    Type: String
    AllowedValues: ['true', 'false']
    Default: 'true'
    Description: |
      - Seleccione true/false para configurar el Delete Protection para Aurora-MySQL Cluster. //
      - La base de datos no se puede eliminar cuando Delete Protection esta habilitada.
# Mappings
Mappings:
  DBEngineMap:
    '5.7.mysql-aurora.2.10.2':
      Engine: 'aurora-mysql'
      EngineVersion: '5.7.mysql_aurora.2.10.2'
      Port: 3306
      ClusterParameterGroupFamily: 'aurora-mysql5.7'
      ParameterGroupFamily: 'aurora-mysql5.7'
    '8.0.mysql-aurora.3.02.0':
      Engine: 'aurora-mysql'
      EngineVersion: '8.0.mysql_aurora.3.02.0'
      Port: 3306
      ClusterParameterGroupFamily: 'aurora-mysql8.0'
      ParameterGroupFamily: 'aurora-mysql8.0'
# Conditions
Conditions:
  HasDBSecretName: !Not [!Equals [!Ref DBSecretName, '']]
  HasDBAutoMinorVersionUpgrade: !Equals [!Ref DBAutoMinorVersionUpgrade, 'true']
  HasDBDeletionProtection: !Equals [!Ref DBDeletionProtection, 'true']
# Resources
Resources:
  # Sercrets Manager
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-secret.html
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-secretsmanager-secret-generatesecretstring.html
  DBSecret:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !If [HasDBSecretName, !Ref DBSecretName, !Ref 'AWS::StackName']
      Description: !Sub "Secret asignado al Aurora-Mysql Cluster del stack ${AWS::StackName}"
      #KmsKeyId: "alias/aws/secretsmanager"
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${DBMasterUsername}"}'
        GenerateStringKey: "password"
        ExcludeCharacters: "/@\"'\\"
        IncludeSpace: false
        PasswordLength: 32  
  SecretRDSInstanceAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref DBSecret
      TargetId: !Ref AuroraDBCluster
      TargetType: AWS::RDS::DBCluster
  # RDS AURORA-MYSQL
  DBClusterSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${AWS::StackName}-sg"
      GroupDescription: !Sub "Permite acceso al Aurora-Mysql Cluster del stack ${AWS::StackName}"
      VpcId: !Ref VpcIdParameter
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !FindInMap [DBEngineMap, !Ref DBEngineVersion, Port]
          ToPort: !FindInMap [DBEngineMap, !Ref DBEngineVersion, Port]
          CidrIp: !Ref DBPermitLocation
          Description: Acceso permitido para CIDR AWS
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-sg"
  DBClusterSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub "${AWS::StackName}-subnetgroup"
      DBSubnetGroupDescription: !Sub "Subnets para uso con Aurora-MySQL Cluster del stack ${AWS::StackName}"
      SubnetIds: !Ref 'DBSubnets'
  DBClusterParameterGroup:
    Type: 'AWS::RDS::DBClusterParameterGroup'
    Properties:
      Description: !Sub "Parameter Group del Aurora-MySQL Cluster del stack ${AWS::StackName}"
      Family: !FindInMap [DBEngineMap, !Ref DBEngineVersion, ClusterParameterGroupFamily]
      Parameters:
        character_set_client: utf8
        character_set_connection: utf8
        character_set_database: utf8
        character_set_filesystem: utf8
        character_set_results: utf8
        character_set_server: utf8
        collation_connection: utf8_general_ci
        collation_server: utf8_general_ci
  AuroraDBCluster:
    Type: AWS::RDS::DBCluster
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Properties:
      DBClusterIdentifier: !Ref DBClusterIdentifierName
      DatabaseName: !Ref DBName
      Engine: !FindInMap [DBEngineMap, !Ref DBEngineVersion, Engine]
      EngineVersion: !FindInMap [DBEngineMap, !Ref DBEngineVersion, EngineVersion]
      EngineMode: provisioned
      BackupRetentionPeriod: !Ref DBBackupRetentionPeriod
      DBClusterParameterGroupName: !Ref DBClusterParameterGroup
      DBSubnetGroupName: !Ref DBClusterSubnetGroup
      Port: !FindInMap [DBEngineMap, !Ref DBEngineVersion, Port]
      MasterUsername: !Sub "{{resolve:secretsmanager:${DBSecret}::username}}"
      MasterUserPassword: !Sub "{{resolve:secretsmanager:${DBSecret}::password}}"
      PreferredBackupWindow: !Ref DBPreferredBackupWindow
      PreferredMaintenanceWindow: !Ref DBPreferredMaintenanceWindow
      DeletionProtection: !If [HasDBDeletionProtection, true, false]
      CopyTagsToSnapshot: true
      StorageEncrypted: true
      VpcSecurityGroupIds: [!Ref DBClusterSecurityGroup]
  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: !Ref 'AWS::StackName'
      Family: !FindInMap [DBEngineMap, !Ref DBEngineVersion, ParameterGroupFamily]
  AuroraDBClusterInstance1:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: !If [HasDBAutoMinorVersionUpgrade, true, false]
      DBClusterIdentifier: !Ref AuroraDBCluster
      DBInstanceClass: !Ref DBInstanceClass
      DBSubnetGroupName: !Ref DBClusterSubnetGroup
      PubliclyAccessible: false
      DBParameterGroupName: !Ref DBParameterGroup
      Engine: !FindInMap [DBEngineMap, !Ref DBEngineVersion, Engine]
  AuroraDBClusterInstance2:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: !If [HasDBAutoMinorVersionUpgrade, true, false]
      DBClusterIdentifier: !Ref AuroraDBCluster
      DBInstanceClass: !Ref DBInstanceClass
      DBSubnetGroupName: !Ref DBClusterSubnetGroup
      PubliclyAccessible: false
      DBParameterGroupName: !Ref DBParameterGroup
      Engine: !FindInMap [DBEngineMap, !Ref DBEngineVersion, Engine]
# Outputs
Outputs:
  ClusterName:
    Description: 'El Nombre del Amazon Aurora-MySQL cluster.'
    Value: !Ref AuroraDBCluster
    Export:
      Name: !Sub '${AWS::StackName}-aurora-mysql-cluster-name'
  ClusterEndpoint:
    Description: 'Aurora Cluster Writer Endpoint'
    Value: !GetAtt 'AuroraDBCluster.Endpoint.Address'
    Export:
      Name: !Sub '${AWS::StackName}-aurora-mysql-cluster-dnsname'
  ReaderEndpoint:
    Description: 'Aurora Cluster Reader Endpoint'
    Value: !GetAtt 'AuroraDBCluster.ReadEndpoint.Address'
    Export:
      Name: !Sub '${AWS::StackName}-aurora-mysql-cluster-readdnsname'
  DBClusterPort:
    Description: 'Aurora Endpoint Port'
    Value: !GetAtt 'AuroraDBCluster.Endpoint.Port'
    Export:
      Name: !Sub '${AWS::StackName}-aurora-mysql-cluster-port'
  DBName:
    Description: 'Nombre de la Base de Datos'
    Value: !Ref DBName
  DBSecurityGroupId:
    Description: 'El security group utilizado para administrar el acceso a RDS Aurora.'
    Value: !Ref DBClusterSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-aurora-mysql-cluster-securitygroupid'
  DBSecretsManagerSecret:
    Description: 'Secret ARN de la base de datos'
    Value: !Ref DBSecret
    Export:
      Name: !Sub '${AWS::StackName}-aurora-mysql-cluster-secret-arn'
...
